## Predicting handmade MNIST samples

In [89]:
import mxnet as mx
import numpy as np
import cv2, time
from IPython.display import Image
from collections import namedtuple

np.set_printoptions(precision=4, suppress=True)

This function loads an image from disk and turns it into a normalized NDArray shaped (1,1,x_size,y_size).

In [90]:
def loadImage(filename):
  img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
  img = img / 255
  img = np.expand_dims(img, axis=0)
  img = np.expand_dims(img, axis=0)
  return mx.nd.array(img)

This function loads an image, forwards it through the model and returns the predicted output.

In [91]:
def predict(model, filename):
  array = loadImage(filename)
  #print(array.shape)
  Batch = namedtuple('Batch', ['data'])
  mod.forward(Batch([array]))
  pred = mod.get_outputs()[0].asnumpy()
  return pred

This function loads a model and prepares it for inference.

In [92]:
def loadModel(model, epochs):
  model, arg_params, aux_params = mx.model.load_checkpoint(model, epochs)
  mod = mx.mod.Module(model)
  mod.bind(for_training=False, data_shapes=[('data', (1,1,28,28))])
  mod.set_params(arg_params, aux_params)
  return mod

In [114]:
#mod = loadModel("mlp", 50)
mod = loadModel("lenet", 25)

/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)


In [115]:
Image(filename="./0.png")

In [116]:
print(predict(mod, "./0.png"))

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [117]:
Image(filename="./1.png")

In [118]:
print(predict(mod, "./1.png"))

[[ 0.      0.9988  0.      0.      0.0004  0.      0.      0.0007  0.0001
   0.    ]]


In [119]:
Image(filename="./2.png")

In [120]:
print(predict(mod, "./2.png"))

[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]


In [121]:
Image(filename="./3.png")

In [122]:
print(predict(mod, "./3.png"))

[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]


In [123]:
Image(filename="./4.png")

In [124]:
print(predict(mod, "./4.png"))

[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [125]:
Image(filename="./5.png")

In [126]:
print(predict(mod, "./5.png"))

[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]


In [127]:
Image(filename="./6.png")

In [128]:
print(predict(mod, "./6.png"))

[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]


In [129]:
Image(filename="./7.png")

In [130]:
print(predict(mod, "./7.png"))

[[ 0.      0.      0.      0.0001  0.      0.      0.      0.9999  0.      0.    ]]


In [131]:
Image(filename="./8.png")

In [132]:
print(predict(mod, "./8.png"))

[[ 0.      0.      0.      0.      0.      0.0096  0.      0.      0.9904
   0.    ]]


In [133]:
Image(filename="./9.png")

In [134]:
print(predict(mod, "./9.png"))

[[ 0.      0.      0.      0.0417  0.0031  0.      0.      0.0001  0.0011
   0.9539]]
